### ISSUE TITLE
Wired memory grows from less than  3GB to more than 10GB over several days - is it ZFS?

### ISSUE THREAD

**Issue by alanruttenberg** [openzfsonosx/zfs#213]
I'm not sure what the best info would be to assess this - let me know. For now I've included the output of zfs list, the output of sysctl zfs after several days, and the output of zdb. When I reboot I'll add another sysctl zfs file to compare. (Why doesn't github let me attach .txt files???)

---

``````
NAME                     USED  AVAIL  REFER  MOUNTPOINT
zfsroot                 3.89T   586G  1.32M  /Volumes/zfsroot
zfsroot/name            283G   586G   283G  -
zfsroot/nameImage       218G  21.8G   218G  /Volumes/nameImage
zfsroot/Commons          206G   707G  85.2G  -
zfsroot/TimeMachine      309G   617G   278G  -
zfsroot/books            168G   132G   168G  /Volumes/books
zfsroot/iPhoto           206G   714G  78.5G  -
zfsroot/iTunes           309G   697G   198G  -
zfsroot/media           1.26T   205G  1.26T  /Volumes/media
zfsroot/media2           986G   114G   986G  /Volumes/media2```

-------

``````

zfs.arc_max: 0
zfs.arc_min: 0
zfs.arc_meta_used: 1702334208
zfs.arc_meta_limit: 3221225472
zfs.l2arc_write_max: 8388608
zfs.l2arc_write_boost: 8388608
zfs.l2arc_headroom: 2
zfs.l2arc_feed_secs: 1
zfs.l2arc_feed_min_ms: 200
zfs.l2arc_noprefetch: 1
zfs.l2arc_feed_again: 1
zfs.l2arc_norw: 0
zfs.anon_size: 18432
zfs.anon_metadata_lsize: 0
zfs.anon_data_lsize: 0
zfs.mru_size: 1998799872
zfs.mru_metadata_lsize: 266654720
zfs.mru_data_lsize: 1604591616
zfs.mru_ghost_size: 2296164352
zfs.mru_ghost_metadata_lsize: 1076072448
zfs.mru_ghost_data_lsize: 1220091904
zfs.mfu_size: 1158606848
zfs.mfu_metadata_lsize: 155009536
zfs.mfu_data_lsize: 974876160
zfs.mfu_ghost_size: 1888160768
zfs.mfu_ghost_metadata_lsize: 259149824
zfs.mfu_ghost_data_lsize: 1629010944
zfs.l2c_only_size: 55236383232
zfs.vnop_osx_debug: 0
zfs.vnop_ignore_negatives: 0
zfs.vnop_ignore_positives: 0
zfs.vnop_create_negatives: 1
zfs.reclaim_list: 0
zfs.vnop_reclaim_throttle: 33280
zfs.vfs_suspend_fs_begin_delay: 2
zfs.vfs_suspend_fs_end_delay: 2
zfs.vnop_force_formd_normalized_output: 0```

---

``````
zfsroot:
    version: 5000
    name: 'zfsroot'
    state: 0
    txg: 5465379
    pool_guid: 11525599921928347233
    errata: 0
    hostid: 3660128869
    hostname: 'localhost'
    vdev_children: 4
    vdev_tree:
        type: 'root'
        id: 0
        guid: 11525599921928347233
        children[0]:
            type: 'mirror'
            id: 0
            guid: 11659360043872116845
            metaslab_array: 38
            metaslab_shift: 34
            ashift: 12
            asize: 2000384688128
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 12789527930152168946
                path: '/dev/disk6s1'
                phys_path: '/dev/diskid/DISK-Y3CN2DTGSp1'
                whole_disk: 1
                DTL: 87
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 9631193934027935819
                path: '/dev/disk3s1'
                phys_path: '/dev/diskid/DISK-Y3CN2E0GSp1'
                whole_disk: 1
                DTL: 85
                create_txg: 4
        children[1]:
            type: 'mirror'
            id: 1
            guid: 1750213957219736340
            metaslab_array: 36
            metaslab_shift: 33
            ashift: 12
            asize: 1500287336448
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 5592394544075990067
                path: '/dev/disk8s1'
                phys_path: '/dev/diskid/DISK-S2HEJX0C900305p1'
                whole_disk: 1
                DTL: 89
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 3468705898681880350
                path: '/dev/disk4s1'
                phys_path: '/dev/diskid/DISK-S2HEJX0CA00263p1'
                whole_disk: 1
                DTL: 83
                create_txg: 4
        children[2]:
            type: 'mirror'
            id: 2
            guid: 18401647215779754242
            metaslab_array: 34
            metaslab_shift: 33
            ashift: 12
            asize: 1500287336448
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 5069286759723677467
                path: '/dev/disk7s1'
                phys_path: '/dev/diskid/DISK-S2HEJ1DB302077p1'
                whole_disk: 1
                DTL: 88
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 12133104694213597855
                path: '/dev/disk5s1'
                phys_path: '/dev/diskid/DISK-S2HEJ1DB302082p1'
                whole_disk: 1
                DTL: 81
                create_txg: 4
        children[3]:
            type: 'disk'
            id: 3
            guid: 1166490624700717247
            path: '/dev/disk1s4'
            phys_path: '/dev/ada7p4'
            whole_disk: 0
            metaslab_array: 116
            metaslab_shift: 25
            ashift: 9
            asize: 5726797824
            is_log: 1
            DTL: 203
            create_txg: 56949
    features_for_read:```
``````
